### ISSUE TITLE
Deanonymization bug

### ISSUE THREAD

**Issue by kewde** [noot/ring-go#6]
Hi,

The key image generation scheme is sadly broken.
This allows for completely de-anonymization.

https://github.com/noot/ring-go/blob/master/ring.go#L181

A similar write up that I did can be found here.
https://kewde.github.io/urs

The hash can not be mapped to the curve using the generator G.

**Comment by kewde** [comment]
I suggest an alternative approach to mapping the hash to a point.
https://github.com/particl/particl-core/blob/master/src/secp256k1/src/modules/mlsag/main_impl.h#L139

**Comment by noot** [comment]
Hey, thanks for pointing this out. I'll look into implementing the alternative.

**Comment by hugolgst** [comment]
Any update?

**Comment by hugolgst** [comment]
Because it is quite a critical issue for the library.

**Comment by noot** [comment]
@hugolgst hey I've been really busy and haven't had much of a chance to maintain this. if you're planning to use the library, I can work on fixing this.

**Comment by kewde** [comment]
@hugolgst 
There are a few libs you can use in Golang that don't have this issue.
https://github.com/dedis/kyber/blob/master/sign/anon/sig.go#L130-L135

**Comment by noot** [comment]
@kewde @hugolgst I believe this should fix the bug, the new `hashToCurve` impl no longer uses the generator to map to the curve. sorry for the extremely late response!
